#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# mcfly (see https://github.com/cantino/mcfly)
if command -v mcfly >/dev/null 2>&1; then
  eval "$(mcfly init zsh)"
fi

# fnox
if command -v fnox >/dev/null 2>&1; then
  eval "$(fnox activate zsh)"
fi

# mise
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

# direnv
if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

# television (https://github.com/alexpasmantier/television)
if command -v tv >/dev/null 2>&1; then
  eval "$(tv init zsh)"
fi

# 1Password plugins & start 1Password CLI daemon to fix issues with direnv
# See: https://github.com/direnv/direnv/issues/662
if command -v op >/dev/null 2>&1 && [[ -r "$HOME/.config/op/plugins.sh" ]]; then
  source "$HOME/.config/op/plugins.sh"
  op daemon -d
fi

# aliases

helpme() {
    printf "%s\n" "$*" | ollama run qwen2.5-coder "output as shell command with a one-line description";
}

alias helpme='helpme'
